package fiddle.all;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

public class RegexUtils {

  public static final String EMAIL_BODY =
      "<!DOCTYPE html>\n"
          + "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:th=\"http://www.thymeleaf.org\">\n"
          + "    <head>\n"
          + "        <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\n"
          + "        <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\n"
          + "        <!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800\" rel=\"stylesheet\" type=\"text/css\" /><!--<![endif]-->\n"
          + "        <!--[if mso]>\n"
          + "        <style type=\"text/css\">\n"
          + "        .fallback-text,a,p,td,span,div,h1,h2,h3 {\n"
          + "        font-family: Helvetica, sans-serif !important;\n"
          + "        }\n"
          + "        </style>\n"
          + "        <![endif]-->\n"
          + "        <!--[if !mso]>\n"
          + "        <meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\" />\n"
          + "        <![endif]-->\n"
          + "        <title></title>\n"
          + "        <style xml:space=\"preserve\">\n"
          + "    @media all {\n"
          + "        table img{\n"
          + "            cursor: default !important;\n"
          + "        }\n"
          + "        table img + div { display:none !important; }\n"
          + "    }\n"
          + "    @media only screen and (min-width: 601px) {\n"
          + "        .desktop-upgrade-box, .desktop-affiliate-box{\n"
          + "            display: table-cell !important;\n"
          + "        }\n"
          + "        .mobile-upgrade-box, .mobile-affiliate-box{\n"
          + "            display: none !important;\n"
          + "        }\n"
          + "        .how-do-know-text{\n"
          + "            padding-right: 0 !important;\n"
          + "            padding-left: 0 !important;\n"
          + "        }\n"
          + "        .desktop-upgrade-box-content,\n"
          + "        .desktop-upgrade-box-img{\n"
          + "            display: table-cell !important;\n"
          + "            vertical-align: top !important;\n"
          + "        }\n"
          + "        .desktop-upgrade-box-img{\n"
          + "            padding: 35px 20px 17px !important;\n"
          + "        }\n"
          + "        .desktop-upgrade-box-img img{\n"
          + "            width: 230px !important;\n"
          + "            height: 159px !important;\n"
          + "        }\n"
          + "        .desktop-upgrade-box-content{\n"
          + "            padding: 0px 30px 0px 0px !important;\n"
          + "        }\n"
          + "        .desktop-upgrade-box-content h2{\n"
          + "            font-size: 20px !important;\n"
          + "            line-height: 26px !important;\n"
          + "            margin-top: 25px !important;\n"
          + "        }\n"
          + "        .desktop-affiliate-box-content,\n"
          + "        .desktop-affiliate-box-img{\n"
          + "            display: table-cell !important;\n"
          + "            vertical-align: top !important;\n"
          + "        }\n"
          + "        .desktop-affiliate-box-img{\n"
          + "            padding: 40px 59px !important;\n"
          + "        }\n"
          + "        .desktop-affiliate-box-img img{\n"
          + "            width: 160px !important;\n"
          + "            height: 113px !important;\n"
          + "        }\n"
          + "        .desktop-affiliate-box-content{\n"
          + "            padding: 0px 30px 0px 0px !important;\n"
          + "        }\n"
          + "        .stTbl,\n"
          + "        .mainTable{\n"
          + "            color: #000000;\n"
          + "        }\n"
          + "        .im,\n"
          + "        td .im,\n"
          + "        div .im,\n"
          + "        p .im,\n"
          + "        span.im,\n"
          + "        strong.im,\n"
          + "        td.im,\n"
          + "        div.im,\n"
          + "        li.im,\n"
          + "        h1.im,\n"
          + "        h2.im,\n"
          + "        h3.im,\n"
          + "        h4.im,\n"
          + "        h5.im,\n"
          + "        p.im{\n"
          + "            color: inherit !important;\n"
          + "        }\n"
          + "        table *,\n"
          + "        table td,\n"
          + "        table p,\n"
          + "        table div,\n"
          + "        table span,\n"
          + "        table strong,\n"
          + "        table li,\n"
          + "        table h1,\n"
          + "        table h2,\n"
          + "        table h3,\n"
          + "        table h4,\n"
          + "        table h5,\n"
          + "        .stTbl *,\n"
          + "        .stTbl td,\n"
          + "        .stTbl p,\n"
          + "        .stTbl div,\n"
          + "        .stTbl span,\n"
          + "        .stTbl strong,\n"
          + "        .stTbl li,\n"
          + "        .stTbl h1,\n"
          + "        .stTbl h2,\n"
          + "        .stTbl h3,\n"
          + "        .stTbl h4,\n"
          + "        .stTbl h5,\n"
          + "        .mainTable *,\n"
          + "        .mainTable td,\n"
          + "        .mainTable p,\n"
          + "        .mainTable div,\n"
          + "        .mainTable span,\n"
          + "        .mainTable strong,\n"
          + "        .mainTable li,\n"
          + "        .mainTable h1,\n"
          + "        .mainTable h2,\n"
          + "        .mainTable h3,\n"
          + "        .mainTable h4,\n"
          + "        .mainTable h5{\n"
          + "            color: inherit;\n"
          + "        }\n"
          + "        .global-footer-promotion-headline{\n"
          + "            font-size: 26px !important;\n"
          + "        }\n"
          + "    }  \n"
          + "    @media only screen and (min-width: 371px) and (max-width: 600px)  {\n"
          + "        .global-footer-promotion-headline{\n"
          + "            font-size: 22px !important;\n"
          + "        }\n"
          + "    } \n"
          + "    .stTbl,\n"
          + "    .mainTable{\n"
          + "        color: #000000;\n"
          + "    }\n"
          + "    .im,\n"
          + "    td .im,\n"
          + "    div .im,\n"
          + "    p .im,\n"
          + "    span.im,\n"
          + "    strong.im,\n"
          + "    td.im,\n"
          + "    div.im,\n"
          + "    li.im,\n"
          + "    h1.im,\n"
          + "    h2.im,\n"
          + "    h3.im,\n"
          + "    h4.im,\n"
          + "    h5.im,\n"
          + "    p.im{\n"
          + "        color: inherit !important;\n"
          + "    }\n"
          + "    table *,\n"
          + "    table td,\n"
          + "    table p,\n"
          + "    table div,\n"
          + "    table span,\n"
          + "    table strong,\n"
          + "    table li,\n"
          + "    table h1,\n"
          + "    table h2,\n"
          + "    table h3,\n"
          + "    table h4,\n"
          + "    table h5,\n"
          + "    .stTbl *,\n"
          + "    .stTbl td,\n"
          + "    .stTbl p,\n"
          + "    .stTbl div,\n"
          + "    .stTbl span,\n"
          + "    .stTbl strong,\n"
          + "    .stTbl li,\n"
          + "    .stTbl h1,\n"
          + "    .stTbl h2,\n"
          + "    .stTbl h3,\n"
          + "    .stTbl h4,\n"
          + "    .stTbl h5,\n"
          + "    .mainTable *,\n"
          + "    .mainTable td,\n"
          + "    .mainTable p,\n"
          + "    .mainTable div,\n"
          + "    .mainTable span,\n"
          + "    .mainTable strong,\n"
          + "    .mainTable li,\n"
          + "    .mainTable h1,\n"
          + "    .mainTable h2,\n"
          + "    .mainTable h3,\n"
          + "    .mainTable h4,\n"
          + "    .mainTable h5{\n"
          + "        color: inherit;\n"
          + "    }\n"
          + "</style>\n"
          + "\n"
          + "        <style type=\"text/css\">\n"
          + "            @media only screen and (min-width: 601px) {\n"
          + "                .hero-image{\n"
          + "                    width: 350px !important;\n"
          + "                    height: 201px !important;\n"
          + "                }\n"
          + "            }\n"
          + "        </style>\n"
          + "        <!--[if gte mso 9]>\n"
          + "        <xml>\n"
          + "        <o:OfficeDocumentSettings>\n"
          + "         <o:AllowPNG/>\n"
          + "         <o:PixelsPerInch>96</o:PixelsPerInch>\n"
          + "        </o:OfficeDocumentSettings>\n"
          + "        </xml>\n"
          + "        <![endif]-->\n"
          + "    </head>\n"
          + "    <body bgcolor=\"#EDEFF0\" leftmargin=\"0\" marginheight=\"0\" marginwidth=\"0\" style=\"font-family: 'Open Sans',Helvetica,sans-serif; mso-line-height-rule: exactly; width: 100%; -webkit-font-smoothing: antialiased; -ms-text-size-adjust: none !important; background: #EDEFF0; margin: 0; padding: 0;\" topmargin=\"0\">\n"
          + "        <div itemscope=\"\" itemtype=\"http://schema.org/EmailMessage\">\n"
          + "          <meta itemprop=\"description\" content=\"View Your Updated Credit Score at WalletHub\"/>\n"
          + "          <div itemprop=\"potentialAction\" itemscope=\"\" itemtype=\"http://schema.org/ViewAction\">\n"
          + "            <link itemprop=\"target url\" href=\"https://efdevhub.info/home/transactions/recurring?utm_source=recurring_reminder&utm_action=VDN&utm_medium=email&groupId=1005&utm_campaign=basic&utm_commid=25126439123&utm_app_version=1.17.0\"/>\n"
          + "            <meta itemprop=\"name\" content=\"Learn More\"/>\n"
          + "          </div>\n"
          + "          <div itemprop=\"publisher\" itemscope=\"\" itemtype=\"http://schema.org/Organization\">\n"
          + "            <meta itemprop=\"name\" content=\"WalletHub\"/>\n"
          + "            <link itemprop=\"url\" href=\"https://wallethub.com\"/>\n"
          + "            <link itemprop=\"url/googlePlus\" href=\"https://plus.google.com/+Wallethub\"/>\n"
          + "          </div>\n"
          + "        </div>\n"
          + "        <style type=\"text/css\" xml:space=\"preserve\">\n"
          + "* {-webkit-text-size-adjust: none}\n"
          + "@media only screen and (max-width: 620px) {\n"
          + "    .mainTable {\n"
          + "        width: 100% !important;\n"
          + "        max-width: 600px !important;\n"
          + "    }\n"
          + "\n"
          + "    .mainTable.tp {\n"
          + "        width: 100% !important;\n"
          + "    }\n"
          + "}\n"
          + "\n"
          + "@media only screen and (max-width: 570px) {\n"
          + "    .new-alert .fp-container {\n"
          + "        width: 47.5% !important;\n"
          + "        display: inline-block !important;\n"
          + "        float: left !important;\n"
          + "        text-align: center !important;\n"
          + "        min-width: 47.5% !important;\n"
          + "    }\n"
          + "\n"
          + "    .new-alert .separator {\n"
          + "        width: 5% !important;\n"
          + "        display: inline-block !important;\n"
          + "        float: left !important;\n"
          + "        height: 100px !important;\n"
          + "    }\n"
          + "\n"
          + "    .new-alert .hide-mob {\n"
          + "        width: 0 !important;\n"
          + "        display: block !important;\n"
          + "        float: none !important;\n"
          + "        clear: both !important;\n"
          + "        height: 30px !important;\n"
          + "    }\n"
          + "    .stTbl,\n"
          + "    .mainTable{\n"
          + "        color: #000000;\n"
          + "    }\n"
          + "    .im,\n"
          + "    td .im,\n"
          + "    div .im,\n"
          + "    p .im,\n"
          + "    span.im,\n"
          + "    strong.im,\n"
          + "    td.im,\n"
          + "    div.im,\n"
          + "    li.im,\n"
          + "    h1.im,\n"
          + "    h2.im,\n"
          + "    h3.im,\n"
          + "    h4.im,\n"
          + "    h5.im,\n"
          + "    p.im{\n"
          + "        color: inherit !important;\n"
          + "    }\n"
          + "    table *,\n"
          + "    table td,\n"
          + "    table p,\n"
          + "    table div,\n"
          + "    table span,\n"
          + "    table strong,\n"
          + "    table li,\n"
          + "    table h1,\n"
          + "    table h2,\n"
          + "    table h3,\n"
          + "    table h4,\n"
          + "    table h5,\n"
          + "    .stTbl *,\n"
          + "    .stTbl td,\n"
          + "    .stTbl p,\n"
          + "    .stTbl div,\n"
          + "    .stTbl span,\n"
          + "    .stTbl strong,\n"
          + "    .stTbl li,\n"
          + "    .stTbl h1,\n"
          + "    .stTbl h2,\n"
          + "    .stTbl h3,\n"
          + "    .stTbl h4,\n"
          + "    .stTbl h5,\n"
          + "    .mainTable *,\n"
          + "    .mainTable td,\n"
          + "    .mainTable p,\n"
          + "    .mainTable div,\n"
          + "    .mainTable span,\n"
          + "    .mainTable strong,\n"
          + "    .mainTable li,\n"
          + "    .mainTable h1,\n"
          + "    .mainTable h2,\n"
          + "    .mainTable h3,\n"
          + "    .mainTable h4,\n"
          + "    .mainTable h5{\n"
          + "        color: inherit;\n"
          + "    }\n"
          + "}\n"
          + "@media only screen and (max-width: 480px) {\n"
          + "  .upgrade .table-half-mob td.fp-container {\n"
          + "    width: 100% !important; display: inline-block !important; float: left !important; text-align: center !important; padding-right: 0 !important; padding-bottom: 0 !important; padding-top: 20px !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob td.fp-container.first {\n"
          + "    padding-top: 40px !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob td.fp-container.last {\n"
          + "    padding-bottom: 30px !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob td.fp-container.last td.icon-container {\n"
          + "    width: 35px !important; padding: 0 8px !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob td.fp-container table {\n"
          + "    width: 100% !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob td.fp-container table td.icon-container {\n"
          + "    text-align: center !important; width: 50px !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob td.fp-container table td.icon-desc {\n"
          + "    text-align: left !important; width: auto !important; color: #7f949c !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob .separator {\n"
          + "    width: 5% !important; display: inline-block !important; float: left !important; height: 25px !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob .hide-mob {\n"
          + "    width: 0 !important; display: block !important; float: none !important; clear: both !important; height: 30px !important;\n"
          + "  }\n"
          + "  .upgrade .table-half-mob .desc {\n"
          + "    padding-bottom: 30px !important; padding-top: 30px !important;\n"
          + "  }\n"
          + "}\n"
          + "@media only screen and (max-width: 500px) {\n"
          + "    .mob-full {\n"
          + "        display: block !important;\n"
          + "        text-align: center !important;\n"
          + "        padding: 0 !important;\n"
          + "        width: 100% !important;\n"
          + "    }\n"
          + "\n"
          + "    .mob-full+.mob-full {\n"
          + "        padding-top: 30px !important;\n"
          + "    }\n"
          + "\n"
          + "    .mob-full+.mob-full.social {\n"
          + "        padding-top: 20px !important;\n"
          + "    }\n"
          + "\n"
          + "    .alert .btn {\n"
          + "        font-size: 13px !important;\n"
          + "    }\n"
          + "\n"
          + "    .app-message .responsiveCell {\n"
          + "        width: 100% !important;\n"
          + "        display: block !important;\n"
          + "    }\n"
          + "\n"
          + "    .app-message .stTbl td {\n"
          + "        vertical-align: top !important;\n"
          + "    }\n"
          + "\n"
          + "    .app-message .profileTbl td {\n"
          + "        padding: 5px 5px 5px 0 !important;\n"
          + "        vertical-align: top !important;\n"
          + "        color: #4bc999 !important;\n"
          + "    }\n"
          + "\n"
          + "    .app-message .profileTbl .label {\n"
          + "        color: #ADBABF !important;\n"
          + "        font-size: 12px !important;\n"
          + "        font-weight: 700 !important;\n"
          + "    }\n"
          + "    .footer .links a{\n"
          + "        font-weight: normal !important;\n"
          + "    }\n"
          + "    .footer .links span{\n"
          + "        letter-spacing: normal !important;\n"
          + "    }\n"
          + "    .new-monthly .hdn p,\n"
          + "    .new-monthly .hdn h1{\n"
          + "        font-size: 17px !important;\n"
          + "        line-height: 25px !important;\n"
          + "    }\n"
          + "    .new-monthly .hdn h1{\n"
          + "        margin: 20px 10px 0px !important;\n"
          + "    }\n"
          + "    .new-monthly .hdn p{\n"
          + "        margin: 0px 0px 20px !important;\n"
          + "    }\n"
          + "    .new-monthly .icon-img,\n"
          + "    .new-monthly .paragraph{\n"
          + "        display: block !important;\n"
          + "        text-align: center !important;\n"
          + "        width: auto !important;\n"
          + "        padding: 25px 0px 0px !important;\n"
          + "    }\n"
          + "    .new-monthly .paragraph{\n"
          + "        padding: 10px 0px 0px !important;\n"
          + "    }\n"
          + "    .new-monthly .paragraph h2{\n"
          + "        font-size: 18px !important;\n"
          + "    }\n"
          + "    .new-monthly .paragraph p{\n"
          + "        font-size: 14px !important;\n"
          + "    }\n"
          + "    .new-monthly .btn{\n"
          + "        font-size: 14px !important;\n"
          + "    }\n"
          + "    .new-monthly .btn td{\n"
          + "        padding: 10px 15px !important;\n"
          + "        width: auto !important;\n"
          + "    }\n"
          + "    .new-monthly .content{\n"
          + "        padding: 0px 10px 0px !important;\n"
          + "    }\n"
          + "    .new-monthly .content-new{\n"
          + "        padding: 0px 10px 30px !important;\n"
          + "    }\n"
          + "    .new-monthly .paragraph .btn{\n"
          + "        margin: 15px auto !important;\n"
          + "    }\n"
          + "    .new-monthly .greeting{\n"
          + "        padding: 0px 10px 0px !important;\n"
          + "    }\n"
          + "    .new-monthly .greeting h1{\n"
          + "        font-size: 18px !important;\n"
          + "        line-height: 25px !important;\n"
          + "    }\n"
          + "    .new-monthly .greeting p{\n"
          + "        font-size: 18px !important;\n"
          + "        line-height: 25px !important;\n"
          + "    }\n"
          + "    .new-monthly .hdn.new{\n"
          + "        padding: 0px 20px !important;\n"
          + "    }\n"
          + "    .new-monthly .hdn.new h1{\n"
          + "        font-size: 20px !important;\n"
          + "        line-height: 25px !important;\n"
          + "        margin: 20px 0px 0px !important ;\n"
          + "    }\n"
          + "    .new-monthly .hdn.new p{\n"
          + "        font-size: 16px !important;\n"
          + "        line-height: 24px !important;\n"
          + "        margin: 0px 0px 25px !important;\n"
          + "    }\n"
          + "    .new-monthly .paragraph h2.intro{\n"
          + "        font-size: 17px !important;\n"
          + "        line-height: 20px !important;\n"
          + "        padding-top: 15px !important;\n"
          + "        padding-bottom: 10px !important;\n"
          + "    }\n"
          + "}\n"
          + ".new-monthly .paragraph h2 a:hover{\n"
          + "    text-decoration: underline !important;\n"
          + "}\n"
          + "@media only screen and (min-width: 601px) {\n"
          + "    .desktop-upgrade-box, .desktop-affiliate-box{\n"
          + "        display: table-cell !important;\n"
          + "    }\n"
          + "    .mobile-upgrade-box, .mobile-affiliate-box{\n"
          + "        display: none !important;\n"
          + "    }\n"
          + "    .how-do-know-text{\n"
          + "        padding-right: 0 !important;\n"
          + "        padding-left: 0 !important;\n"
          + "    }\n"
          + "    .desktop-upgrade-box-content,\n"
          + "    .desktop-upgrade-box-img{\n"
          + "        display: table-cell !important;\n"
          + "        vertical-align: top !important;\n"
          + "    }\n"
          + "    .desktop-upgrade-box-img{\n"
          + "        padding: 35px 20px 17px !important;\n"
          + "    }\n"
          + "    .desktop-upgrade-box-img img{\n"
          + "        width: 230px !important;\n"
          + "        height: 159px !important;\n"
          + "    }\n"
          + "    .desktop-upgrade-box-content{\n"
          + "        padding: 0px 30px 0px 0px !important;\n"
          + "    }\n"
          + "    .desktop-upgrade-box-content h2{\n"
          + "        font-size: 20px !important;\n"
          + "        line-height: 26px !important;\n"
          + "        margin-top: 25px !important;\n"
          + "    }\n"
          + "    .stTbl,\n"
          + "    .mainTable{\n"
          + "        color: #000000;\n"
          + "    }\n"
          + "    .im,\n"
          + "    td .im,\n"
          + "    div .im,\n"
          + "    p .im,\n"
          + "    span.im,\n"
          + "    strong.im,\n"
          + "    td.im,\n"
          + "    div.im,\n"
          + "    li.im,\n"
          + "    h1.im,\n"
          + "    h2.im,\n"
          + "    h3.im,\n"
          + "    h4.im,\n"
          + "    h5.im,\n"
          + "    p.im{\n"
          + "        color: inherit !important;\n"
          + "    }\n"
          + "    table *,\n"
          + "    table td,\n"
          + "    table p,\n"
          + "    table div,\n"
          + "    table span,\n"
          + "    table strong,\n"
          + "    table li,\n"
          + "    table h1,\n"
          + "    table h2,\n"
          + "    table h3,\n"
          + "    table h4,\n"
          + "    table h5,\n"
          + "    .stTbl *,\n"
          + "    .stTbl td,\n"
          + "    .stTbl p,\n"
          + "    .stTbl div,\n"
          + "    .stTbl span,\n"
          + "    .stTbl strong,\n"
          + "    .stTbl li,\n"
          + "    .stTbl h1,\n"
          + "    .stTbl h2,\n"
          + "    .stTbl h3,\n"
          + "    .stTbl h4,\n"
          + "    .stTbl h5,\n"
          + "    .mainTable *,\n"
          + "    .mainTable td,\n"
          + "    .mainTable p,\n"
          + "    .mainTable div,\n"
          + "    .mainTable span,\n"
          + "    .mainTable strong,\n"
          + "    .mainTable li,\n"
          + "    .mainTable h1,\n"
          + "    .mainTable h2,\n"
          + "    .mainTable h3,\n"
          + "    .mainTable h4,\n"
          + "    .mainTable h5{\n"
          + "        color: inherit;\n"
          + "    }\n"
          + "    .global-footer-promotion-headline{\n"
          + "        font-size: 26px !important;\n"
          + "    }\n"
          + "}  \n"
          + "@media only screen and (min-width: 371px) and (max-width: 600px)  {\n"
          + "    .global-footer-promotion-headline{\n"
          + "        font-size: 22px !important;\n"
          + "    }\n"
          + "}  \n"
          + ".stTbl,\n"
          + ".mainTable{\n"
          + "    color: #000000;\n"
          + "}\n"
          + ".im,\n"
          + "td .im,\n"
          + "div .im,\n"
          + "p .im,\n"
          + "span.im,\n"
          + "strong.im,\n"
          + "td.im,\n"
          + "div.im,\n"
          + "li.im,\n"
          + "h1.im,\n"
          + "h2.im,\n"
          + "h3.im,\n"
          + "h4.im,\n"
          + "h5.im,\n"
          + "p.im{\n"
          + "    color: inherit !important;\n"
          + "}\n"
          + "table *,\n"
          + "table td,\n"
          + "table p,\n"
          + "table div,\n"
          + "table span,\n"
          + "table strong,\n"
          + "table li,\n"
          + "table h1,\n"
          + "table h2,\n"
          + "table h3,\n"
          + "table h4,\n"
          + "table h5,\n"
          + ".stTbl *,\n"
          + ".stTbl td,\n"
          + ".stTbl p,\n"
          + ".stTbl div,\n"
          + ".stTbl span,\n"
          + ".stTbl strong,\n"
          + ".stTbl li,\n"
          + ".stTbl h1,\n"
          + ".stTbl h2,\n"
          + ".stTbl h3,\n"
          + ".stTbl h4,\n"
          + ".stTbl h5,\n"
          + ".mainTable *,\n"
          + ".mainTable td,\n"
          + ".mainTable p,\n"
          + ".mainTable div,\n"
          + ".mainTable span,\n"
          + ".mainTable strong,\n"
          + ".mainTable li,\n"
          + ".mainTable h1,\n"
          + ".mainTable h2,\n"
          + ".mainTable h3,\n"
          + ".mainTable h4,\n"
          + ".mainTable h5{\n"
          + "    color: inherit;\n"
          + "}\n"
          + "</style>\n"
          + "\n"
          + "        <!-- Start: Wrapper -->\n"
          + "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"stTbl\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%; max-width: 100%;\" width=\"100%\">\n"
          + "            <tr>\n"
          + "                <td bgcolor=\"#EDEFF0\" class=\"stTbl\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; border-spacing: 0; width: 100%; max-width: 100%;\" valign=\"top\" width=\"100%\">\n"
          + "                    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mainTable\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%; font-family: Helvetica,Arial,sans-serif; max-width: 600px; margin: 0 auto;\">\n"
          + "                        <!-- Start: Header -->\n"
          + "                        <tr>\n"
          + "    <td align=\"left\" bgcolor=\"#EDEFF0\" style=\"text-align: left;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;background: transparent;color: transparent; line-height: 20px;\" height=\"10\" valign=\"bottom\">&nbsp;</td>\n"
          + "</tr>\n"
          + "\n"
          + "                        <tr>\n"
          + "    <td align=\"left\" bgcolor=\"#23123a\" style=\"text-align: left; min-width: 100%; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; font-size: 0;\" valign=\"bottom\">\n"
          + "        <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;margin: 0; padding: 0; width: 100%;\">\n"
          + "            <tbody>\n"
          + "                <tr>\n"
          + "                        <td bgcolor=\"#ffc219\" style=\"vertical-align: top; width: 55px; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; font-size: 0px; color:#ffffff;text-align: center; font-weight: bold; line-height: normal;font-family: Helvetica,sans-serif,Arial; padding: 0px; color: #fff;\" valign=\"top\" width=\"55\" align=\"center\">\n"
          + "                            <img src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/premium-w-icon.png\" alt=\"W\" width=\"55\" height=\"55\" style=\"width: 55px; height: 55px; vertical-align: top; -ms-interpolation-mode: bicubic; border: 0 none; margin: 0 auto; font-size: 30px; line-height: 25px;\" valign=\"top\" align=\"center\" />\n"
          + "                        </td>\n"
          + "                    <td bgcolor=\"#23123a\" style=\"vertical-align: middle; text-align: left; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; font-size: 0px; color:#ffffff;font-weight: bold; line-height: normal;font-family: Helvetica,sans-serif,Arial; padding-left: 14px; color: #fff;\" valign=\"middle\"><img src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/w-text_Vb08aa27_.png\" alt=\"WalletHub\" style=\"width: 101px; height: 20px; vertical-align: middle; -ms-interpolation-mode: bicubic; border: 0 none; margin: 0px; font-size: 22px;\" width=\"101\" height=\"20\" valign=\"middle\" />\n"
          + "                    </td>\n"
          + "                </tr>\n"
          + "            </tbody>\n"
          + "        </table>\n"
          + "    </td>\n"
          + "</tr>\n"
          + "\n"
          + "                        <!-- End: Header -->\n"
          + "                        <!-- Start: Main -->\n"
          + "                        <tr>\n"
          + "                            <td align=\"left\" bgcolor=\"#EDEFF0\" style=\"text-align: left; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;\" valign=\"bottom\">\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"mainTable upgrade-box\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%; font-family: 'Open Sans',Helvetica,sans-serif; max-width: 100%; color: #000000; margin: 0 auto;\">\n"
          + "                                   \n"
          + "                                    <tr>\n"
          + "                                        <td class=\"hero-section\" style=\"padding: 36px 20px 0;background: white;\">\n"
          + "                                            <table style=\"border-spacing: 0;width: 100%;\">\n"
          + "                                                <tr>\n"
          + "                                                    <td align=\"center\">  \n"
          + "                                                        <img class=\"hero-image\" src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/recurring-bills.png\" alt=\"all-accounts-in-one-place\" width=\"270\" height=\"154\" style=\"width: 270px; height: 154px; vertical-align: middle; -ms-interpolation-mode: bicubic; border: 0 none;\" valign=\"center\" align=\"center\"/>\n"
          + "                                                    </td>\n"
          + "                                                </tr>\n"
          + "                                                <tr>\n"
          + "                                                    <td class=\"hdn\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; margin: 0 auto; padding-top: 56px;font-size: 16px;line-height: 22px;font-family: 'Open Sans',Helvetica,sans-serif;\">\n"
          + "                                                        <p style=\"font-size: 16px; margin: 0px; padding: 0px; font-weight: normal;text-align: left;line-height: 24px;font-family: 'Open Sans',Helvetica,sans-serif;\">\n"
          + "                                                                <span>Hi Donna,</span>\n"
          + "                                                        </p>\n"
          + "                                                    </td>\n"
          + "                                                </tr>\n"
          + "                                                <tr>\n"
          + "                                                    <td class=\"body-text\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; padding: 23px 0 20px;font-family: 'Open Sans',Helvetica,sans-serif;\">\n"
          + "                                                        <p style=\"line-height: 24px; font-size: 16px; margin: 0; padding: 0;\">\n"
          + "                                                            As requested, we would like to remind you of the following upcoming due dates:\n"
          + "                                                        </p>\n"
          + "                                                            <ul style=\"margin-top: 0; margin-bottom: 0;padding-left: 20px;padding-top: 10px;\">\n"
          + "                                                                        <li style=\"line-height: 24px; font-size: 16px; padding-top: 10px;\">\n"
          + "                                                                            <strong>Uber:</strong> Mar 01\n"
          + "                                                                        </li>\n"
          + "                                                            </ul>\n"
          + "\n"
          + "                                                    </td>\n"
          + "                                                </tr>\n"
          + "                                                <tr>\n"
          + "                                                    <td class=\"btn-wrapper\" valign=\"top\" align=\"left\" width=\"100%\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;padding: 28px 0px;\">\n"
          + "\n"
          + "                                                        <table class=\"btn-table\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" bgcolor=\"#136AE8\" class=\"btn\" style=\"border-spacing: 0; border-collapse: separate; mso-table-lspace: 0; mso-table-rspace: 0; font-family: 'Open Sans',Helvetica,sans-serif; font-size: 16px; border-radius: 5px; text-align: center; text-decoration: none; vertical-align: middle; width: 100%;margin: 0;background: #ffffff;\" width=\"100%\">\n"
          + "                                                            <tbody>\n"
          + "                                                                <tr>\n"
          + "\n"
          + "\n"
          + "                                                                    <!--[if mso]>\n"
          + "                                                                    <td style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; -moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 5px; vertical-align: top; border-color: #136ae8;border-style: solid;border-width: 12px 13px; background: #136ae8;color: #ffffff; text-align: center;\" valign=\"top\">\n"
          + "                                                                        <a  href=\"https://efdevhub.info/home/transactions/recurring?utm_source=recurring_reminder&utm_action=VDN&utm_medium=email&groupId=1005&utm_campaign=basic&utm_commid=25126439123&utm_app_version=1.17.0\" style=\"color: #ffffff; display: block; text-decoration: none; font-weight: bold;font-family: 'Open Sans',Helvetica,sans-serif;\">\n"
          + "                                                                            View Details Now\n"
          + "                                                                        </a>\n"
          + "                                                                    </td>\n"
          + "                                                                    <![endif]--> \n"
          + "\n"
          + "                                                                    <!--[if !mso]>-->\n"
          + "                                                                    <td style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; -moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 5px; vertical-align: top; background: #136ae8;color: #ffffff; text-align: center;\" valign=\"top\">\n"
          + "                                                                        <a  href=\"https://efdevhub.info/home/transactions/recurring?utm_source=recurring_reminder&utm_action=VDN&utm_medium=email&groupId=1005&utm_campaign=basic&utm_commid=25126439123&utm_app_version=1.17.0\" style=\"color: #ffffff; display: block; text-decoration: none; font-weight: bold;font-family: 'Open Sans',Helvetica,sans-serif;padding: 12px 13px;\">\n"
          + "                                                                            View Details Now\n"
          + "                                                                        </a>\n"
          + "                                                                    </td>\n"
          + "                                                                    <!--<![endif]-->\n"
          + "                                                                </tr>\n"
          + "                                                            </tbody>\n"
          + "                                                        </table>\n"
          + "                                                    </td>\n"
          + "                                                </tr>\n"
          + "                                            </table>\n"
          + "                                        </td>\n"
          + "                                    </tr>\n"
          + "                                </table>\n"
          + "                            </td>\n"
          + "                        </tr>\n"
          + "                        <!-- End: Main -->\n"
          + "                        <!-- Start: Footer -->\n"
          + "                            <tr>\n"
          + "    <td style=\"padding-top: 20px;\"  class=\"desktop-affiliate-box\">\n"
          + "        <div style=\"padding-top: 30px;height: 0px; background: #EDEFF0;\"></div>\n"
          + "        <table bgcolor=\"#FFF\" style=\"border-spacing: 0; width: 100%; background: #ffffff;\">\n"
          + "            <tr>\n"
          + "                <td style=\"vertical-align: top; padding: 0px; background: #ffffff;\">\n"
          + "                <div style=\"display:block; padding: 26px 15px 0px; text-align: center;\" class=\"desktop-affiliate-box-img\">\n"
          + "                    <img src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/invite-friends.png\" alt=\"invite-friends\" width=\"207\" height=\"146\" style=\"width: 207px; height: 146px; vertical-align: middle; -ms-interpolation-mode: bicubic; border: 0 none;margin: 0 auto;\" valign=\"center\" align=\"center\"/>\n"
          + "                </div>\n"
          + "                <div style=\"padding: 0px 15px 0px;display: block;\" class=\"desktop-affiliate-box-content\">\n"
          + "                    <h2 style=\"font-family:'Open Sans',Helvetica,sans-serif;font-weight: 700;font-size: 20px;line-height: 26px;margin: 25px 0 0; color: #000000;\">Invite Your Friends</h2>\n"
          + "                    <p style=\"font-family:'Open Sans',Helvetica,sans-serif;font-weight: 400;font-size: 16px;line-height: 24px;margin: 10px 0 0; color: #000000;\">Get your friends to sign up for WalletHub Premium and earn $20 for each qualifying referral.</p>\n"
          + "                    <a href=\"https://efdevhub.info/settings/invite?utm_source=affiliate-footer&utm_action=affiliate-link&utm_medium=email&utm_campaign=basic&groupid=1005&utm_commid=25126439123\" style=\"color: #136AE8; text-decoration: none;font-family: 'Open Sans',Helvetica,sans-serif;font-size: 16px;line-height: 32px;margin-top: 10px;display: block;margin-bottom: 25px;font-weight: bold;\">\n"
          + "                        Learn More \n"
          + "                        <img src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/blue-chev-4x.png\" alt=\">\"  height=\"12\" style=\"width: auto; height: 12px; vertical-align: middle; -ms-interpolation-mode: bicubic; border: 0 none; margin-left: 4px;margin-top: -3px;\" valign=\"center\" align=\"center\"/>\n"
          + "                    </a>\n"
          + "                </div>\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "        </table>     \n"
          + "    </td>\n"
          + "</tr>\n"
          + "<tr>\n"
          + "    <td align=\"left\" bgcolor=\"#EDEFF0\" style=\"text-align: left; min-width: 100%; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;\" valign=\"bottom\">\n"
          + "        <div class=\"split\" style=\"line-height: 20px;background: #EDEFF0;\">\n"
          + "            &nbsp;\n"
          + "        </div>\n"
          + "        <div class=\"split\" style=\"line-height: 30px;background: #EDEFF0;\">\n"
          + "            &nbsp;\n"
          + "        </div>\n"
          + "        <table align=\"center\" bgcolor=\"#EDEFF0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mainTable footer\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%; font-family: 'Open Sans',Helvetica,sans-serif; max-width: 100%; text-align: center; font-size: 14px; background: #edeff0; margin: 0 auto; padding: 0px 10px;\">\n"
          + "            <tbody>\n"
          + "            <tr>\n"
          + "                <td align=\"center\" class=\"footer-logo\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; text-align: center; color: #000000; height: 30px; padding-bottom: 15px;\"><a href=\"https://apps.apple.com/us/app/wallethub/id1110552982?mt=8\" style=\"letter-spacing: normal; text-decoration: none;\" target=\"_blank\"><img src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/appstore_Vdeab012_.png\" style=\"-ms-interpolation-mode: bicubic; border: 0;\" alt=\"Download on the AppStore\" /></a><span>&nbsp;&nbsp;</span><a href=\"https://play.google.com/store/apps/details?id=com.wallethub.mywallet\" style=\"letter-spacing: normal; text-decoration: none;\" target=\"_blank\"><img src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/playstore_Va824995_.png\" style=\"-ms-interpolation-mode: bicubic; border: 0;\" alt=\"Download on the PlayStore\" /></a></td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"left\" style=\"text-align: left; min-width: 100%; border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;background: transparent;\n"
          + "                font-family:'Open Sans',Helvetica,sans-serif;font-weight: normal;line-height: 20px; font-size: 14px;color: #000000; padding: 40px 15px 30px;\" valign=\"bottom\" class=\"how-do-know-text\">\n"
          + "                <p style=\"line-height: 20px; font-size: 14px; padding: 0; margin: 0px;font-family: 'Open Sans',Helvetica,sans-serif; font-weight: 600;color: #000000;\">How do I know this email is from WalletHub?</p>\n"
          + "                <p style=\"text-align: left; font-family:'Open Sans',Helvetica,sans-serif;font-weight: normal;line-height: 20px; font-size: 14px;color: #000000; margin: 0px;padding: 0px;\">Links in this email will start with: \"<a style=\"text-decoration: none; cursor: default;color: #000000 !important;\" href=\"#\"><font color=\"#000000\">https://wallethub.com</font></a>\". When you click on a link, you will land on either <a style=\"text-decoration: none; cursor: default;color: #000000 !important;\" href=\"#\"><font color=\"#000000\">wallethub.com</font></a> - where you will see a padlock icon (<img width=\"12\" height=\"12\" alt=\"padlock icon\" src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/posts/109074/email_locked.png\" style=\"width: 12px; height: 12px; vertical-align: middle; display: inline-block;\" />) in the top left of the address bar of your browser - or on the WalletHub mobile app.</p>\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"center\">\n"
          + "                    <img src=\"https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/black-w-icon.png\" alt=\"W\" width=\"30\" height=\"30\" style=\"width: 30px; height: 30px; vertical-align: center; -ms-interpolation-mode: bicubic; border: 0 none; margin: 16px auto 13px; \" valign=\"center\" align=\"center\"/>\n"
          + "                </td>\n"
          + "            </tr>   \n"
          + "            <tr>\n"
          + "                <td align=\"center\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; text-align: center; color: #000000;font-family: 'Open Sans',Helvetica,sans-serif;\">\n"
          + "                    Copyright &#169; <span>2025</span> Evolution Finance, Inc\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"center\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; text-align: center; color: #000000;font-family: 'Open Sans',Helvetica,sans-serif;\">\n"
          + "                    <a style=\"color:#000000 !important; text-decoration:none !important;font-family: 'Open Sans',Helvetica,sans-serif;\">&#8203;&zwnj; 150 SE 2nd Ave, Suite 300, Miami, FL 33131</a>\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"center\" class=\"links\" style=\"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; text-align: center; color: #136AE8; padding-top: 15px; padding-bottom: 50px;\">\n"
          + "                    <a href=\"https://efdevhub.info/home/settings?utm_position=footer&amp;groupid=1005&amp;utm_commid=25126439123&amp;key=ef690a5f449996856d1e34e1f8a2b309d747651d5b3b4a4c5a901e6ebcbf61d8&amp;first=1\" style=\"color: #136AE8; text-decoration: none;font-family: 'Open Sans',Helvetica,sans-serif;\" target=\"_blank\">Settings</a>\n"
          + "                    <span style=\"letter-spacing: 2px; color: #B4B4B4;\">&nbsp;|&nbsp;</span>\n"
          + "                    <a href=\"https://efdevhub.info/unsubscribe?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YWxsZXRodWIiLCJleHAiOjE3NzIwNTE5NzcsIkVtYWlsVHlwZSI6IlJlY3VycmluZ19UcmFuc2FjdGlvbl9SZW1pbmRlciIsIktleSI6ImVuYy5rZXk6MjAyMi0wNi0wMTw6PkJpVDUwU3VxRWtnS0dXdUhmSTd0SkdzeHZQQ1Z6Mmx2Q2lVWURDK0QvUnM9In0.nMQ7u7UnvcguS3780Qp-fA1DdKpHmQhRulwonI6u0SQ&amp;ref=d3e339ec-acdb-4568-ae8f-727bc4980944&amp;utm_commid=25126439123&amp;groupid=1005\" style=\"text-decoration:none;color:#136AE8;font-family: 'Open Sans',Helvetica,sans-serif;\" target=\"_blank\">Unsubscribe</a>\n"
          + "                    <span style=\"letter-spacing: 2px; color: #B4B4B4;\">&nbsp;|&nbsp;</span>\n"
          + "                    <a href=\"https://efdevhub.info/terms/?utm_position=footer&amp;groupid=1005&amp;utm_commid=25126439123&amp;key=ef690a5f449996856d1e34e1f8a2b309d747651d5b3b4a4c5a901e6ebcbf61d8&amp;first=1\" style=\"color: #136AE8; text-decoration: none;font-family: 'Open Sans',Helvetica,sans-serif;\" target=\"_blank\">Terms</a>\n"
          + "                    <span style=\"letter-spacing: 2px; color: #B4B4B4;\">&nbsp;|&nbsp;</span>\n"
          + "                    <a href=\"https://efdevhub.info/terms/privacy?utm_position=footer&amp;groupid=1005&amp;utm_commid=25126439123&amp;key=ef690a5f449996856d1e34e1f8a2b309d747651d5b3b4a4c5a901e6ebcbf61d8&amp;first=1\" style=\"color: #136AE8; text-decoration: none;font-family: 'Open Sans',Helvetica,sans-serif;\" target=\"_blank\">Privacy</a>\n"
          + "                                    </td>\n"
          + "            </tr>\n"
          + "            </tbody>\n"
          + "        </table>\n"
          + "        <img style=\"width: 1px; height: 1px; position:absolute;visibility:hidden;left:0;bottom:0\" src=\"https://efdevhub.info/pixel.png?utm_commid=25126439123&r=mvwFtUkdX56K4voy6c9SgACTaPKPzUtV\" />\n"
          + "    </td>\n"
          + "</tr>\n"
          + "\n"
          + "                        <!-- End: Footer -->\n"
          + "                    </table>\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "        </table>\n"
          + "        <!-- End: Wrapper -->\n"
          + "    </body>\n"
          + "</html>";

  public static void main(String[] args) {
    String[] texts =
        new String[] {
          "$50.00 payment due on Mar 01, 2025; full statement balance is $100.",
          "$50.00 payment due on Mar 01, 2025. Edit",
          " $50.00 payment due on Mar 07; full statement balance is ."
        };
    for (String text : texts) {
      System.out.println(extractUsingRegex(text, "\\$(.*) payment due on"));
      System.out.println(extractUsingRegex(text, "due on ([^.^;]*)"));
      System.out.println(extractUsingRegex(text, "full statement balance is \\$(.*)\\."));

      System.out.println("<<<>>>");
    }
    System.out.println(
        extractUsingRegex(
            "API response: {\"responses\":[{\"private_id\":2131478674,\"email\":\"ef_1741285257118@evolutionfinance.com\",\"status\":\"SUCCESS\"}]}\n",
            "\"private_id\":(\\d*),"));

    System.out.println(
        extractUsingRegex("$50 payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex(
            "$70 minimum payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex("$50.00 payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex(
            "$70.00 minimum payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex("$-50 payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex(
            "$-70 minimum payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex("$-50.00 payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex(
            "$-70.00 minimum payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex("-$50 payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex(
            "-$70 minimum payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex("-$50.00 payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
    System.out.println(
        extractUsingRegex(
            "-$70.00 minimum payment due on", "\\$([\\d-,.]*) (minimum )?payment due on"));
  }

  public static List<String> extractUsingRegex(String text, String regex) {
    var compile = Pattern.compile(regex);
    var matcher = compile.matcher(text);
    List<String> allFound = new ArrayList<>();
    while (matcher.find()) {
      int count = matcher.groupCount();
      for (int i = 0; i < count; i++) {
        allFound.add(matcher.group(i + 1));
      }
    }
    return allFound;
  }
}
