package fiddle;


import java.util.regex.Pattern;

public class RegexUtils {

  public static void main(String[] args) {
    var emailBody = EMAIL_BODY;
    extractUsingRegex(emailBody, "<.*href=\"([^\"]*)\".*>\\s*\\n*View Details Now");
    extractUsingRegex(emailBody, "<.*href=\"([^\"]*)\".*>\\s*\\n*Settings");
    extractUsingRegex(emailBody, "<.*href=\"([^\"]*)\".*>\\s*\\n*Terms");
    extractUsingRegex(emailBody, "<.*href=\"([^\"]*)\".*>\\s*\\n*Privacy");
    extractUsingRegex(emailBody, "<.*href=\"([^\"]*)\".*>\\s*\\n*Unsubscribe");
    extractUsingRegex(emailBody, "(Large Transaction at New Merchant)");
  }

  public static String extractUsingRegex(String email, String regex) {
    var compile = Pattern.compile(regex);
    var matcher = compile.matcher(email);
    String extractedValue = null;
    if (matcher.find()) {
      extractedValue = matcher.group(1);
    }
    System.out.println(extractedValue);
    return extractedValue;
  }

  public static final String EMAIL_BODY =
      "<td bgcolor=\"#EDEFF0\" class=\"m_-3427288324074859585stTbl\" style=\"border-collapse:collapse;border-spacing:0;width:100%;max-width:100%\" valign=\"top\" width=\"100%\">\n"
          + "                    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"m_-3427288324074859585mainTable\" style=\"border-spacing:0;border-collapse:collapse;width:100%;font-family:Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto\">\n"
          + "                        \n"
          + "                        <tbody><tr>\n"
          + "    <td align=\"left\" bgcolor=\"#EDEFF0\" style=\"text-align:left;min-width:100%;border-collapse:collapse;background:transparent;color:transparent;line-height:20px\" height=\"10\" valign=\"bottom\">&nbsp;</td>\n"
          + "</tr>\n"
          + "\n"
          + "                        <tr>\n"
          + "    <td align=\"left\" bgcolor=\"#23123a\" style=\"text-align:left;min-width:100%;border-collapse:collapse;font-size:0\" valign=\"bottom\">\n"
          + "        <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing:0;border-collapse:collapse;margin:0;padding:0;width:100%\">\n"
          + "            <tbody>\n"
          + "                <tr>\n"
          + "                        <td bgcolor=\"#ffc219\" style=\"vertical-align:top;width:55px;border-collapse:collapse;font-size:0px;color:#ffffff;text-align:center;font-weight:bold;line-height:normal;font-family:Helvetica,sans-serif,Arial;padding:0px;color:#fff\" valign=\"top\" width=\"55\" align=\"center\">\n"
          + "                            <img src=\"https://ci3.googleusercontent.com/meips/ADKq_NZyh2abX_3OQfVijJ-2oPtXwb-hUkh8MD-csR9VWfHDYAQkCS7zMKKbUzWY3Ww5NPxCwdqBIw9-aIgxbtX-I3L_0JysAGGDWbfSfcZ_HgKNl3Em94LbVLyDwJc45zmp8JUfH_C7HLBCZs6cZM0=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/premium-w-icon.png\" alt=\"W\" width=\"55\" height=\"55\" style=\"width:55px;height:55px;vertical-align:top;border:0 none;margin:0 auto;font-size:30px;line-height:25px\" valign=\"top\" align=\"center\" class=\"CToWUd\" data-bit=\"iit\">\n"
          + "                        </td>\n"
          + "                    <td bgcolor=\"#23123a\" style=\"vertical-align:middle;text-align:left;border-collapse:collapse;font-size:0px;color:#ffffff;font-weight:bold;line-height:normal;font-family:Helvetica,sans-serif,Arial;padding-left:14px;color:#fff\" valign=\"middle\"><img src=\"https://ci3.googleusercontent.com/meips/ADKq_NZKf4xU-il_9omhwQ2ygLEeyC2bZcVfDZ3oKT2kKEN3TzNtTWh-YLtDdYe8-HhmjpFp_9PIbC5YSYxt5ZUgKEeEgf0iIeaMUgA5xl2AQh2FFHuAgZNKKTyKGtE6TJaFsKYhD_qcojQgYa1iA1Cmuw=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/w-text_Vb08aa27_.png\" alt=\"WalletHub\" style=\"width:101px;height:20px;vertical-align:middle;border:0 none;margin:0px;font-size:22px\" width=\"101\" height=\"20\" valign=\"middle\" class=\"CToWUd\" data-bit=\"iit\">\n"
          + "                    </td>\n"
          + "                </tr>\n"
          + "            </tbody>\n"
          + "        </table>\n"
          + "    </td>\n"
          + "</tr>\n"
          + "\n"
          + "                        \n"
          + "                        \n"
          + "                        <tr>\n"
          + "                            <td align=\"left\" bgcolor=\"#EDEFF0\" style=\"text-align:left;border-collapse:collapse\" valign=\"bottom\">\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"m_-3427288324074859585mainTable\" style=\"border-spacing:0;border-collapse:collapse;width:100%;font-family:'Open Sans',Helvetica,sans-serif;max-width:100%;color:#000000;margin:0 auto\">\n"
          + "                                    <tbody><tr>\n"
          + "                                        <td align=\"center\" bgcolor=\"#ffffff\" style=\"border-collapse:collapse;padding:33px 20px 39px\">\n"
          + "                                            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"m_-3427288324074859585stTbl\" style=\"border-spacing:0;border-collapse:collapse;width:100%;font-family:'Open Sans',Helvetica,sans-serif;max-width:590px;margin:0 auto;color:#000000\">\n"
          + "                                                <tbody>\n"
          + "                                                    <tr>\n"
          + "                                                        <td style=\"border-collapse:collapse;margin:0 auto\">\n"
          + "                                                            <p style=\"font-size:16px;margin:0px;padding:0px;font-weight:normal;text-align:left;line-height:24px;font-family:'Open Sans',Helvetica,sans-serif\">\n"
          + "                                                                    <span>Hi Robert,</span>\n"
          + "                                                            </p>\n"
          + "                                                        </td>\n"
          + "                                                    </tr>\n"
          + "                                                    <tr>\n"
          + "                                                        <td style=\"border-collapse:collapse;padding:23px 0 29px;font-family:'Open Sans',Helvetica,sans-serif\">\n"
          + "                                                            <p style=\"line-height:24px;font-size:16px;margin:0;padding:0\">\n"
          + "                                                                Based on your <a href=\"https://efdevhub.info/identity-protection/manage-alerts?utm_source=budgeting-transaction&amp;utm_action=billing&amp;utm_medium=email&amp;groupId=642&amp;utm_campaign=basic&amp;utm_position=main&amp;utm_commid=25125927536\" style=\"color:#136ae8;text-decoration:none;font-family:'Open Sans',Helvetica,sans-serif\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://efdevhub.info/identity-protection/manage-alerts?utm_source%3Dbudgeting-transaction%26utm_action%3Dbilling%26utm_medium%3Demail%26groupId%3D642%26utm_campaign%3Dbasic%26utm_position%3Dmain%26utm_commid%3D25125927536&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw2mzJiIINSNF9qW15uwsRQo\">preferences</a>, we generated the following alerts:\n"
          + "                                                            </p>\n"
          + "                                                                <ul style=\"margin-top:0;margin-bottom:0;padding-left:20px;padding-top:10px\">\n"
          + "                                                                        <li style=\"line-height:24px;font-size:16px;padding-top:10px\">\n"
          + "                                                                            <strong>Large Transaction at New Merchant:</strong>\n"
          + "                                                                            $1,500 at 'Target Mall' with your 'Capital One Credit Card' on Oct 23, 2024.\n"
          + "                                                                        </li>\n"
          + "                                                                        <li style=\"line-height:24px;font-size:16px;padding-top:10px\">\n"
          + "                                                                            <strong>Large Transaction at New Merchant:</strong>\n"
          + "                                                                            $6,500 at 'Amazon 123' with your 'Capital One Credit Card' on Oct 23, 2024.\n"
          + "                                                                        </li>\n"
          + "                                                                </ul>\n"
          + "                                                        </td>\n"
          + "                                                    </tr>\n"
          + "                                                    <tr>\n"
          + "                                                        <td valign=\"top\" align=\"left\" width=\"100%\" style=\"border-collapse:collapse\">\n"
          + "\n"
          + "                                                            <table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#136AE8\" style=\"border-spacing:0;border-collapse:separate;font-family:'Open Sans',Helvetica,sans-serif;font-size:18px;border-radius:5px;text-align:center;text-decoration:none;vertical-align:middle;width:100%;margin:0;background:#ffffff\" width=\"100%\">\n"
          + "                                                                <tbody>\n"
          + "                                                                    <tr>\n"
          + "                                                                        <td style=\"border-collapse:collapse;border-radius:5px;vertical-align:top;border-color:#136ae8;border-style:solid;border-width:10px 13px;background:#136ae8;color:#ffffff;text-align:center\" valign=\"top\">\n"
          + "                                                                            <a href=\"https://efdevhub.info/transactions?other=Triggered%20an%20Alert&amp;utm_source=budgeting-transaction&amp;utm_action=view_details_now&amp;utm_medium=email&amp;utm_campaign=basic&amp;utm_position=main&amp;groupId=642&amp;utm_commid=25125927536\" style=\"color:#ffffff;display:block;text-decoration:none;font-family:'Open Sans',Helvetica,sans-serif\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://efdevhub.info/transactions?other%3DTriggered%2520an%2520Alert%26utm_source%3Dbudgeting-transaction%26utm_action%3Dview_details_now%26utm_medium%3Demail%26utm_campaign%3Dbasic%26utm_position%3Dmain%26groupId%3D642%26utm_commid%3D25125927536&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw3RtAGeqMyiWhbV6NhgJckQ\">\n"
          + "                                                                                View Details Now\n"
          + "                                                                            </a>\n"
          + "                                                                        </td>\n"
          + "                                                                    </tr>\n"
          + "                                                                </tbody>\n"
          + "                                                            </table>\n"
          + "                                                        </td>\n"
          + "                                                    </tr>\n"
          + "                                                </tbody>\n"
          + "                                            </table>\n"
          + "                                        </td>\n"
          + "                                    </tr>\n"
          + "                                </tbody></table>\n"
          + "                            </td>\n"
          + "                        </tr>\n"
          + "                        \n"
          + "                        \n"
          + "                            <tr>\n"
          + "    <td style=\"padding-top:20px\" class=\"m_-3427288324074859585desktop-affiliate-box\">\n"
          + "        <div style=\"padding-top:30px;height:0px;background:#edeff0\"></div>\n"
          + "        <table bgcolor=\"#FFF\" style=\"border-spacing:0;width:100%;background:#ffffff\">\n"
          + "            <tbody><tr>\n"
          + "                <td style=\"vertical-align:top;padding:0px;background:#ffffff\">\n"
          + "                <div style=\"display:block;padding:26px 15px 0px;text-align:center\" class=\"m_-3427288324074859585desktop-affiliate-box-img\">\n"
          + "                    <img src=\"https://ci3.googleusercontent.com/meips/ADKq_NZIxxIcZVRqm9t9djH7kJvsPzoDzK9v7EegEgLZ8Df_bHDPGppu4VYwq9l8oGNLVNxJDDj_Kl8W137xu6n8WWFX0TP_2K5RqyirKD2FL5NEOQtHMzr9l-_87pJyq0cp8UPc8Kk7m3Nv6Ru3PuA=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/invite-friends.png\" alt=\"invite-friends\" width=\"207\" height=\"146\" style=\"width:207px;height:146px;vertical-align:middle;border:0 none;margin:0 auto\" valign=\"center\" align=\"center\" class=\"CToWUd a6T\" data-bit=\"iit\" tabindex=\"0\"><div class=\"a6S\" dir=\"ltr\" style=\"opacity: 0.01; left: 663px; top: 843px;\"><span data-is-tooltip-wrapper=\"true\" class=\"a5q\" jsaction=\"JIbuQc:.CLIENT\"><button class=\"VYBDae-JX-I VYBDae-JX-I-ql-ay5-ays CgzRE\" jscontroller=\"PIVayb\" jsaction=\"click:h5M12e; clickmod:h5M12e;pointerdown:FEiYhc;pointerup:mF5Elf;pointerenter:EX0mI;pointerleave:vpvbp;pointercancel:xyn4sd;contextmenu:xexox;focus:h06R8; blur:zjh6rb;mlnRJb:fLiPzd;\" data-idom-class=\"CgzRE\" jsname=\"hRZeKc\" aria-label=\"Download attachment \" data-tooltip-enabled=\"true\" data-tooltip-id=\"tt-c264\" data-tooltip-classes=\"AZPksf\" id=\"\" jslog=\"91252; u014N:cOuCgd,Kr2w4b,xr6bB; 4:WyIjbXNnLWY6MTgxMzcwNDEyMjg0NDMyMDgzNSJd; 43:WyJpbWFnZS9qcGVnIl0.\"><span class=\"OiePBf-zPjgPe VYBDae-JX-UHGRz\"></span><span class=\"bHC-Q\" jscontroller=\"LBaJxb\" jsname=\"m9ZlFb\" soy-skip=\"\" ssk=\"6:RWVI5c\"></span><span class=\"VYBDae-JX-ank-Rtc0Jf\" jsname=\"S5tZuc\" aria-hidden=\"true\"><span class=\"bzc-ank\" aria-hidden=\"true\"><svg viewBox=\"0 -960 960 960\" height=\"20\" width=\"20\" focusable=\"false\" class=\" aoH\"><path d=\"M480-336L288-528l51-51L444-474V-816h72v342L621-579l51,51L480-336ZM263.72-192Q234-192 213-213.15T192-264v-72h72v72H696v-72h72v72q0,29.7-21.16,50.85T695.96-192H263.72Z\"></path></svg></span></span><div class=\"VYBDae-JX-ano\"></div></button><div class=\"ne2Ple-oshW8e-J9\" id=\"tt-c264\" role=\"tooltip\" aria-hidden=\"true\">Download</div></span></div>\n"
          + "                </div>\n"
          + "                <div style=\"padding:0px 15px 0px;display:block\" class=\"m_-3427288324074859585desktop-affiliate-box-content\">\n"
          + "                    <h2 style=\"font-family:'Open Sans',Helvetica,sans-serif;font-weight:700;font-size:20px;line-height:26px;margin:25px 0 0;color:#000000\">Invite Your Friends</h2>\n"
          + "                    <p style=\"font-family:'Open Sans',Helvetica,sans-serif;font-weight:400;font-size:16px;line-height:24px;margin:10px 0 0;color:#000000\">Get your friends to sign up for WalletHub Premium and earn $10 for each qualifying referral.</p>\n"
          + "                    <a href=\"https://efdevhub.info/settings/invite?utm_source=affiliate-footer&amp;utm_action=affiliate-link&amp;utm_medium=email&amp;utm_campaign=basic&amp;groupid=642&amp;utm_commid=25125927536\" style=\"color:#136ae8;text-decoration:none;font-family:'Open Sans',Helvetica,sans-serif;font-size:16px;line-height:32px;margin-top:10px;display:block;margin-bottom:25px;font-weight:bold\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://efdevhub.info/settings/invite?utm_source%3Daffiliate-footer%26utm_action%3Daffiliate-link%26utm_medium%3Demail%26utm_campaign%3Dbasic%26groupid%3D642%26utm_commid%3D25125927536&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw0FfYxfcbGyS-O7X8wjn0EA\">\n"
          + "                        Learn More \n"
          + "                        <img src=\"https://ci3.googleusercontent.com/meips/ADKq_NaWP7VBTbAbwpgNr1RuRcfcera97JTqQy57wMOQjVVhk0ir03oVF4WNG4oEkhBy0E8X4bF3MUh9o5OV86TKBYmPPhy55u24R8J9PwEKcHxL34T7PUTwzpHAOxG47rdDFwASj6g7KT1b4iDP=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/blue-chev-4x.png\" alt=\">\" height=\"12\" style=\"width:auto;height:12px;vertical-align:middle;border:0 none;margin-left:4px\" valign=\"center\" align=\"center\" class=\"CToWUd\" data-bit=\"iit\">\n"
          + "                    </a>\n"
          + "                </div>\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "        </tbody></table>     \n"
          + "    </td>\n"
          + "</tr>\n"
          + "<tr>\n"
          + "    <td align=\"left\" bgcolor=\"#EDEFF0\" style=\"text-align:left;min-width:100%;border-collapse:collapse\" valign=\"bottom\">\n"
          + "        <div style=\"line-height:20px;background:#edeff0\">\n"
          + "            &nbsp;\n"
          + "        </div>\n"
          + "        <div style=\"line-height:30px;background:#edeff0\">\n"
          + "            &nbsp;\n"
          + "        </div>\n"
          + "        <table align=\"center\" bgcolor=\"#EDEFF0\" cellpadding=\"0\" cellspacing=\"0\" class=\"m_-3427288324074859585mainTable\" style=\"border-spacing:0;border-collapse:collapse;width:100%;font-family:'Open Sans',Helvetica,sans-serif;max-width:100%;text-align:center;font-size:14px;background:#edeff0;margin:0 auto;padding:0px 10px\">\n"
          + "            <tbody>\n"
          + "            <tr>\n"
          + "                <td align=\"center\" style=\"border-collapse:collapse;text-align:center;color:#000000;height:30px;padding-bottom:15px\"><a href=\"https://apps.apple.com/us/app/wallethub/id1110552982?mt=8\" style=\"letter-spacing:normal;text-decoration:none\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://apps.apple.com/us/app/wallethub/id1110552982?mt%3D8&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw1nUeupyTb31r9WN92_Xo20\"><img src=\"https://ci3.googleusercontent.com/meips/ADKq_NY-dMYG-ZjczF3ZjxwHgz8HbZuexAqmf9T-kj7qEhGuCI53Z-bViuHwErpaYyoO33nDh5_s1FE5tFxTD-3ntEzw8pqs9Vbaux6fcbDqL2JFH8t3RdBgbFII9mIJbMsnHdmBks-OL1yiU9pUUVMyCRxt=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/appstore_Vdeab012_.png\" style=\"border:0\" alt=\"Download on the AppStore\" class=\"CToWUd\" data-bit=\"iit\"></a><span>&nbsp;&nbsp;</span><a href=\"https://play.google.com/store/apps/details?id=com.wallethub.mywallet\" style=\"letter-spacing:normal;text-decoration:none\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://play.google.com/store/apps/details?id%3Dcom.wallethub.mywallet&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw0EcQuC3OZNJo-ocRz8LQK5\"><img src=\"https://ci3.googleusercontent.com/meips/ADKq_NZO-arwzqA3ZhXsI2D7S0yB1h4eEAUCjdYi7lh1hp_8gReCSbmGywvN5tfpMwziHpdKkds4A4U-ZViqXvutcMLQ5soUViVCF2GhMKIvX8Oi4e6yWrCBGbNn-5XUPQSZcMXMUagApkOVHOe0ZwghPqC9RA=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/playstore_Va824995_.png\" style=\"border:0\" alt=\"Download on the PlayStore\" class=\"CToWUd\" data-bit=\"iit\"></a></td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"left\" style=\"text-align:left;min-width:100%;border-collapse:collapse;background:transparent;font-family:'Open Sans',Helvetica,sans-serif;font-weight:normal;line-height:20px;font-size:14px;color:#000000;padding:40px 15px 30px\" valign=\"bottom\" class=\"m_-3427288324074859585how-do-know-text\">\n"
          + "                <p style=\"line-height:20px;font-size:14px;padding:0;margin:0px;font-family:'Open Sans',Helvetica,sans-serif;font-weight:600;color:#000000\">How do I know this email is from WalletHub?</p>\n"
          + "                <p style=\"text-align:left;font-family:'Open Sans',Helvetica,sans-serif;font-weight:normal;line-height:20px;font-size:14px;color:#000000;margin:0px;padding:0px\">Links in this email will start with: \"<a style=\"text-decoration:none;color:#000000!important\" href=\"#m_-3427288324074859585_\"><font color=\"#000000\">https://wallethub.com</font></a>\". When you click on a link, you will land on either <a style=\"text-decoration:none;color:#000000!important\" href=\"#m_-3427288324074859585_\"><font color=\"#000000\">wallethub.com</font></a> - where you will see a padlock icon (<img width=\"12\" height=\"12\" alt=\"padlock icon\" src=\"https://ci3.googleusercontent.com/meips/ADKq_NbYlBJDsL0mPwTpcrBSr54YjjFWMcXmwlfGGNFmQnbb0_-DxBgOeZWeadX9RtJTJToiv0my1cIH-QM5pP9HYTSHnEQIN-x4wf4XWlWJU6F6S8kQgaeMDwNBLDMZIT1SoJw_Vw=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/posts/109074/email_locked.png\" style=\"width:12px;height:12px;vertical-align:middle;display:inline-block\" class=\"CToWUd\" data-bit=\"iit\">) in the top left of the address bar of your browser - or on the WalletHub mobile app.</p>\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"center\">\n"
          + "                    <img src=\"https://ci3.googleusercontent.com/meips/ADKq_Nbwg3yV48jACqibzZqXFV6Yx1Hy8b2BeRipEzD2g4CcDyrGpeCdC2XQxXPMtKPei5YrsBlP1bIbIj-oEB5k2XwEcBS23SFlPMF_83U7kzcCXMkqSklBzFv-J-PtnQiXkdQqjd1VIWJYTa3t=s0-d-e1-ft#https://d3pe5qb06dym3o.cloudfront.net/wallethub/images/wh2015/emails/black-w-icon.png\" alt=\"W\" width=\"30\" height=\"30\" style=\"width:30px;height:30px;vertical-align:center;border:0 none;margin:16px auto 13px\" valign=\"center\" align=\"center\" class=\"CToWUd\" data-bit=\"iit\">\n"
          + "                </td>\n"
          + "            </tr>   \n"
          + "            <tr>\n"
          + "                <td align=\"center\" style=\"border-collapse:collapse;text-align:center;color:#000000;font-family:'Open Sans',Helvetica,sans-serif\">\n"
          + "                    Copyright © <span>2024</span> Evolution Finance, Inc\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"center\" style=\"border-collapse:collapse;text-align:center;color:#000000;font-family:'Open Sans',Helvetica,sans-serif\">\n"
          + "                    <a style=\"color:#000000!important;text-decoration:none!important;font-family:'Open Sans',Helvetica,sans-serif\">\u200B\u200C 150 SE 2nd ave, Suite 300, Miami, FL 33131</a>\n"
          + "                </td>\n"
          + "            </tr>\n"
          + "            <tr>\n"
          + "                <td align=\"center\" style=\"border-collapse:collapse;text-align:center;color:#136ae8;padding-top:15px;padding-bottom:50px\">\n"
          + "                    <a href=\"https://efdevhub.info/home/settings?utm_position=footer&amp;groupid=642&amp;utm_commid=25125927536&amp;key=31b554a9e41a91a6e6ea4c6b7f37993bd31056760bf026911410d4b43106f464&amp;first=1\" style=\"color:#136ae8;text-decoration:none;font-family:'Open Sans',Helvetica,sans-serif\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://efdevhub.info/home/settings?utm_position%3Dfooter%26groupid%3D642%26utm_commid%3D25125927536%26key%3D31b554a9e41a91a6e6ea4c6b7f37993bd31056760bf026911410d4b43106f464%26first%3D1&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw05asKXrHu4Gu4NaB9FUUwk\">Settings</a>\n"
          + "                    <span style=\"letter-spacing:2px;color:#b4b4b4\">&nbsp;|&nbsp;</span>\n"
          + "                    <a href=\"https://efdevhub.info/unsubscribe?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YWxsZXRodWIiLCJleHAiOjE3NjEyMTkwMzcsIkVtYWlsVHlwZSI6IkFsZXJ0c19CdWRnZXRpbmdUcmFuc2FjdGlvbnMiLCJLZXkiOiJlbmMua2V5OjIwMjItMDYtMDE8Oj5lZC9PWWV2WmUwZGx6cm1hSmVBcFl6WE5rZVE3U0lTZzNKampwZWhQYTdvPSJ9.cuIWayy03Xo3Fj3cXCGO20Q-jMc-P10kX9sRIltEJpA&amp;ref=c282cc29-eb27-4150-b65c-195ed9e01f87&amp;utm_commid=25125927536&amp;groupid=642\" style=\"text-decoration:none;color:#136ae8;font-family:'Open Sans',Helvetica,sans-serif\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://efdevhub.info/unsubscribe?key%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YWxsZXRodWIiLCJleHAiOjE3NjEyMTkwMzcsIkVtYWlsVHlwZSI6IkFsZXJ0c19CdWRnZXRpbmdUcmFuc2FjdGlvbnMiLCJLZXkiOiJlbmMua2V5OjIwMjItMDYtMDE8Oj5lZC9PWWV2WmUwZGx6cm1hSmVBcFl6WE5rZVE3U0lTZzNKampwZWhQYTdvPSJ9.cuIWayy03Xo3Fj3cXCGO20Q-jMc-P10kX9sRIltEJpA%26ref%3Dc282cc29-eb27-4150-b65c-195ed9e01f87%26utm_commid%3D25125927536%26groupid%3D642&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw04ypPn8X3bM3TAgAR1O-dt\">Unsubscribe</a>\n"
          + "                    <span style=\"letter-spacing:2px;color:#b4b4b4\">&nbsp;|&nbsp;</span>\n"
          + "                    <a href=\"https://efdevhub.info/terms/?utm_position=footer&amp;groupid=642&amp;utm_commid=25125927536&amp;key=31b554a9e41a91a6e6ea4c6b7f37993bd31056760bf026911410d4b43106f464&amp;first=1\" style=\"color:#136ae8;text-decoration:none;font-family:'Open Sans',Helvetica,sans-serif\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://efdevhub.info/terms/?utm_position%3Dfooter%26groupid%3D642%26utm_commid%3D25125927536%26key%3D31b554a9e41a91a6e6ea4c6b7f37993bd31056760bf026911410d4b43106f464%26first%3D1&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw0OJ3_KSVwj3vnkvnncDgSz\">Terms</a>\n"
          + "                    <span style=\"letter-spacing:2px;color:#b4b4b4\">&nbsp;|&nbsp;</span>\n"
          + "                    <a href=\"https://efdevhub.info/terms/privacy?utm_position=footer&amp;groupid=642&amp;utm_commid=25125927536&amp;key=31b554a9e41a91a6e6ea4c6b7f37993bd31056760bf026911410d4b43106f464&amp;first=1\" style=\"color:#136ae8;text-decoration:none;font-family:'Open Sans',Helvetica,sans-serif\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://efdevhub.info/terms/privacy?utm_position%3Dfooter%26groupid%3D642%26utm_commid%3D25125927536%26key%3D31b554a9e41a91a6e6ea4c6b7f37993bd31056760bf026911410d4b43106f464%26first%3D1&amp;source=gmail&amp;ust=1729778519778000&amp;usg=AOvVaw0hOKGmZL28S3Yu9tzFLxKE\">Privacy</a>\n"
          + "                                    </td>\n"
          + "            </tr>\n"
          + "            </tbody>\n"
          + "        </table>\n"
          + "        <img style=\"width:1px;height:1px\" src=\"https://efdevhub.info/pixel.png?utm_commid=25125927536&amp;r=5JL2xhQMjNVE4ptwhuB7r0ckNlMG3ADE\" class=\"CToWUd\" data-bit=\"iit\">\n"
          + "    </td>\n"
          + "</tr>\n"
          + "\n"
          + "                        \n"
          + "                    </tbody></table>\n"
          + "                </td>";
}
